######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 22 14:49:56 2019
######################################################################

TEMPLATE = subdirs

SUBDIRS += \
    lib.pro \
    test_vector.pro \
    test_ray.pro \
    test_sphere_circle.pro

CONFIG += ordered
